env:
  browser: true
  es2021: true
  node: true
root: true
extends:
  - "eslint:recommended"
  - "plugin:vue/essential"
  - "prettier"
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - vue
rules: {}
